services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bwchef2
      MYSQL_USER: bwchef2
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  spring-app:
    build:
      context: ./bwchef_backend
    container_name: bwchef_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bwchef2
      SPRING_DATASOURCE_USERNAME: bwchef2
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysql

  react-app:
    build:
      context: ./bwchef_frontend
    container_name: bwchef_frontend
    ports:
      - "80:80"
    depends_on:
      - spring-app
volumes:
  mysql-data:
